-- PostgreSQL. Aplicar antes de usar a agenda; reexecução preserva os eventos.
BEGIN;
CREATE TABLE IF NOT EXISTS EventoAgenda (
    id_evento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(120) NOT NULL CHECK (length(trim(titulo)) > 0),
    tipo varchar(20) NOT NULL CHECK (tipo IN ('ATENDIMENTO','VISITA','REUNIAO','PIA','AUDIENCIA','RELATORIO','OUTRO')),
    data_evento date NOT NULL,
    hora_inicio time NOT NULL,
    hora_fim time NOT NULL CHECK (hora_fim > hora_inicio),
    local_evento varchar(160) NOT NULL DEFAULT '',
    observacoes text NOT NULL DEFAULT '',
    status varchar(15) NOT NULL DEFAULT 'AGENDADO' CHECK (status IN ('AGENDADO','CONCLUIDO','CANCELADO')),
    cpf_adolescente bigint REFERENCES Adolescente(cpf_adolescente),
    cpf_equipe bigint REFERENCES EquipeTecnica(cpf_equipe)
);
CREATE INDEX IF NOT EXISTS idx_agenda_data ON EventoAgenda(data_evento,hora_inicio);
COMMIT;
