-- Relatório mensal com cópia dos dados revisados; não altera Documento nem relatórios antigos.
BEGIN;
CREATE TABLE IF NOT EXISTS RelatorioAcompanhamento (
    id_relatorio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_adolescente bigint NOT NULL REFERENCES Adolescente(cpf_adolescente),
    competencia date NOT NULL,
    data_emissao date NOT NULL,
    nome text NOT NULL,
    nascimento text NOT NULL DEFAULT '',
    filiacao text NOT NULL DEFAULT '',
    responsavel text NOT NULL DEFAULT '',
    endereco text NOT NULL DEFAULT '',
    telefone text NOT NULL DEFAULT '',
    telefone_responsavel text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    processo text NOT NULL DEFAULT '',
    horas text NOT NULL DEFAULT '',
    registro_frequencia text NOT NULL DEFAULT '',
    descumprimento text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_relatorio_adolescente_competencia ON RelatorioAcompanhamento(cpf_adolescente,competencia);
COMMIT;
